'''
Modify the starter code below to create your own cool drawing
and then Pull Request it to your instructor. Make sure you
keep the last two lines of code. Your first and last name must be written on your art.
The last line keeps the window open until you click to close.

Turtle Documentation: https://docs.python.org/3.3/library/turtle.html?highlight=turtle

'''
import turtle
tina = turtle.Turtle()
tommy = turtle.Turtle()
tina.color('black')
tommy.color('black')
tina.shape('turtle')
tommy.shape('turtle')
tina.speed(50)
tina.speed(50)
tina.penup()
tina.goto(-75,40)
tina.pendown()
tina.color('brown')
tina.begin_fill()
tina.goto(-95,40)
tina.goto(-98,35)
tina.goto(-102,30)
tina.goto(-103,20)
tina.goto(-103,-8)
tina.goto(-98,-10)
tina.goto(-95,-14)
tina.goto(-78,-18)
tina.end_fill()
tina.penup()
tina.goto(125,40)
tina.pendown()
tina.color('brown')
tina.begin_fill()
tina.goto(140,40)
tina.goto(145,35)
tina.goto(150,25)
tina.goto(150,-8)
tina.goto(145,-10)
tina.goto(140,-14)
tina.goto(135,-16)
tina.goto(130,-18)
tina.end_fill()
tina.penup()
tommy.penup()
tommy.color('tan')
tommy.goto(25,-115)
tommy.pendown()
tommy.begin_fill()
tommy.circle(110)
tommy.end_fill()
tommy.penup()

tommy.color('black')
tommy.penup()
tommy.goto(-30,0)
tommy.pendown()
tommy.circle(25)
tommy.penup()

tommy.goto(75,0)
tommy.pendown()
tommy.circle(25)

tommy.penup()
tommy.color('pink')
tommy.goto(60,-100)
tommy.pendown()
tommy.begin_fill()
tommy.circle(10)
tommy.end_fill()

tommy.penup()
tommy.color('black')
tommy.goto(30,-30)
tommy.pendown()
tommy.begin_fill()
tommy.circle(10)
tommy.end_fill()
tommy.goto(40,-65)
tommy.begin_fill()
tommy.goto(10,-65)
tommy.goto(10,-80)
tommy.goto(70,-80)
tommy.goto(70,-65)
tommy.goto(10,-65)
tommy.end_fill()
tommy.penup()
tommy.penup()
tommy.goto(-85,20)
tommy.begin_fill()
tommy.pendown()
tommy.goto(-92,20)
tommy.goto(-92,0)
tommy.goto(-85,0)
tommy.end_fill()
tommy.penup()
tommy.goto(-18,8)
tommy.pendown()
tommy.begin_fill()
tommy.circle(13)
tommy.penup()
tommy.end_fill()
tommy.goto(86,9)
tommy.pendown()
tommy.begin_fill()
tommy.circle(13)
tommy.end_fill()

tina.color('black')
tina.goto(130,20)
tina.pendown()
tina.begin_fill()
tina.goto(142,20)
tina.goto(142,-5)
tina.goto(135,-5)
tina.end_fill()
tina.penup()
tina.goto(0,0)

tommy.penup()
tommy.goto(-100,-100)
tina.goto(-100,-100)

tommy.goto(-80,150)
tommy.write('Oded Harazi 2022                                    Monkey')
tommy.goto(-100,-100)
tina.goto(-100,-100)

