'''
Modify the starter code below to create your own cool drawing
and then Pull Request it to your instructor. Make sure you
keep the last two lines of code. Your first and last name must be written on your art.
The last line keeps the window open until you click to close.

Turtle Documentation: https://docs.python.org/3.3/library/turtle.html?highlight=turtle

'''
import turtle
yoda=turtle.Turtle()
screen=turtle.Screen() # makes a screen object
screen.bgcolor('aqua') # colors the screen
yoda.pensize(1) # width of pen line
yoda.speed(2)  # speed of drawing. Go fast to not waste time.
yoda.color("yellow") # edge of box is 350,335
yoda.penup()
yoda.goto(280,230)
yoda.pendown()
yoda.begin_fill()
yoda.circle(50)
yoda.end_fill()
yoda.penup()
yoda.goto(-360,0)
yoda.color("blue")
yoda.pendown()
yoda.begin_fill()
yoda.goto(360,0)
yoda.goto(360,-360)
yoda.goto(-360,-360)
yoda.goto(-360,0)
yoda.end_fill()
yoda.penup()
yoda.color("brown")
yoda.pencolor("black")
yoda.pensize(3)
yoda.begin_fill()
yoda.goto(-90,0)
yoda.pendown()
yoda.goto(90,0)
yoda.goto(125,60)
yoda.goto(60,50)
yoda.goto(40,30)
yoda.goto(-110,33)
yoda.goto(-90,0)
yoda.end_fill()
yoda.penup()
yoda.goto(0,30)
yoda.color("white")
yoda.pencolor("black")
yoda.pendown()
yoda.begin_fill()
yoda.goto(0,100)
yoda.goto(70,105)
yoda.goto(70,51)
yoda.goto(60,50)
yoda.goto(40,30)
yoda.goto(0,30)
yoda.end_fill()
yoda.penup()
yoda.goto(40,60)
yoda.pendown()
yoda.pensize(1.5)
yoda.color("grey")
yoda.pencolor("black")
yoda.begin_fill()
yoda.circle(15)
yoda.end_fill()
yoda.penup()
yoda.goto(40,63)
yoda.pendown()
yoda.color("teal")
yoda.pencolor("black")
yoda.begin_fill()
yoda.circle(12)
yoda.end_fill()
yoda.penup()
yoda.pensize(3)
yoda.color("red")
yoda.pencolor("black")
yoda.goto(-10,100)
yoda.pendown()
yoda.begin_fill()
yoda.goto(80,105)
yoda.goto(80,118)
yoda.goto(-10,113)
yoda.goto(-10,100)
yoda.end_fill()
yoda.color("brown")
yoda.pencolor("black")
yoda.penup()
yoda.goto(0,43)
yoda.pendown()
yoda.begin_fill()
yoda.goto(-80,46)
yoda.goto(-75,32)
yoda.goto(0,30)
yoda.goto(0,43)
yoda.end_fill()
yoda.penup()
yoda.color("grey")
yoda.pencolor("black")
yoda.goto(15,114)
yoda.pendown()
yoda.begin_fill()
yoda.goto(15,137)
yoda.goto(27,137)
yoda.goto(27,115)
yoda.goto(15,114)
yoda.end_fill()
yoda.goto(15,137)
yoda.begin_fill()
yoda.goto(5,137)
yoda.goto(5,149)
yoda.goto(37,149)
yoda.goto(37,137)
yoda.goto(15,137)
yoda.end_fill()
yoda.color("white")
yoda.pencolor("white")
yoda.penup()
yoda.goto(-280,230)
yoda.pendown()
yoda.begin_fill()
yoda.circle(30)
yoda.end_fill()
yoda.penup()
yoda.goto(-240,230)
yoda.pendown()
yoda.begin_fill()
yoda.circle(30)
yoda.end_fill()
yoda.penup()
yoda.goto(-200,230)
yoda.pendown()
yoda.begin_fill()
yoda.circle(30)
yoda.end_fill()
yoda.penup()
yoda.goto(-260,200)
yoda.pendown()
yoda.begin_fill()
yoda.circle(30)
yoda.end_fill()
yoda.penup()
yoda.goto(-220,200)
yoda.pendown()
yoda.begin_fill()
yoda.circle(30)
yoda.end_fill()
yoda.penup()
yoda.goto(-260,260)
yoda.pendown()
yoda.begin_fill()
yoda.circle(30)
yoda.end_fill()
yoda.penup()
yoda.goto(-220,260)
yoda.pendown()
yoda.begin_fill()
yoda.circle(30)
yoda.end_fill()
yoda.penup()
yoda.goto(30,230)
yoda.pendown()
yoda.begin_fill()
yoda.circle(20)
yoda.end_fill()
yoda.penup()
yoda.goto(60,230)
yoda.pendown()
yoda.begin_fill()
yoda.circle(20)
yoda.end_fill()
yoda.penup()
yoda.goto(90,230)
yoda.pendown()
yoda.begin_fill()
yoda.circle(20)
yoda.end_fill()
yoda.penup()
yoda.goto(45,210)
yoda.pendown()
yoda.begin_fill()
yoda.circle(20)
yoda.end_fill()
yoda.penup()
yoda.goto(75,210)
yoda.pendown()
yoda.begin_fill()
yoda.circle(20)
yoda.end_fill()
yoda.penup()
yoda.goto(45,250)
yoda.pendown()
yoda.begin_fill()
yoda.circle(20)
yoda.end_fill()
yoda.penup()
yoda.goto(75,250)
yoda.pendown()
yoda.begin_fill()
yoda.circle(20)
yoda.end_fill()










yoda.penup()
yoda.goto(200,-200)
yoda.write('Owen Earp',font=("Arial", 16, "normal")) # signs your name to your art
turtle.exitonclick() #Keeps pycharm window open so we can see the drawing
