'''
Modify the starter code below to create your own cool drawing
and then Pull Request it to your instructor.

Turtle Documentation: https://docs.python.org/3.3/library/turtle.html?highlight=turtle

'''
import turtle
tina = turtle.Turtle()
tina.shape('turtle')

tina.speed(15)
tina.penup()
tina.goto(30,-150)
tina.color('purple')
tina.begin_fill()
tina.pendown()
tina.circle(150)
tina.end_fill()
tina.penup()
tina.color('white')
tina.goto(-30,50)
tina.penup()
tina.goto(-115,-4)
tina.begin_fill()
tina.pendown()
tina.pensize(10)
tina.color('black')
tina.forward(290)
tina.end_fill()
tina.pensize(2)
tina.begin_fill()
tina.color('black')
tina.penup()
tina.goto(30,-45)
tina.pendown()
tina.circle(50)
tina.end_fill()
tina.penup()
tina.goto(29,-27)
tina.begin_fill()
tina.pendown()
tina.color('white')
tina.circle(30)
tina.end_fill()
tina.penup()
tina.goto(-12,70)
tina.left(60)
tina.pendown()
tina.pensize(7)
tina.forward(50)
tina.right(120)
tina.forward(35)
tina.left(120)
tina.forward(35)
tina.right(120)
tina.forward(50)
tina.penup()
tina.goto(100,130)
tina.right(29)
tina.color('hot pink')
tina.pendown()
tina.forward(50)
tina.left(90)
tina.forward(50)
tina.penup()
tina.goto(-46,126)
tina.right(90)
tina.pendown()
tina.forward(50)
tina.right(90)
tina.forward(50)
tina.penup()
tina.goto(-100,-100)
tina.color('black')
tina.pensize()
tina.write("Master Ball")


turtle.exitonclick() #Keeps pycharm window open
