'''
Modify the starter code below to create your own cool drawing
and then Pull Request it to your instructor.

Turtle Documentation: https://docs.python.org/3.3/library/turtle.html?highlight=turtle

'''
import turtle

pencil = turtle
pencil.penup()
pencil.speed(10)
shading = (72,30,9)

pencil.color("#252525")
pencil.goto(0,75)
pencil.pendown()
pencil.shape("circle")
pencil.shapesize(25,15,10)
pencil.stamp()
pencil.shape("turtle")
pencil.shapesize(1,1,1)
pencil.penup()
pencil.color("red")
pencil.pensize(12)
pencil.goto(0,-150)
pencil.begin_fill()
pencil.pendown()
pencil.circle(150)
pencil.end_fill()
pencil.penup()
pencil.goto(-150,0)
pencil.right(90)
pencil.color("white")
pencil.pendown()
pencil.begin_fill()
pencil.circle(150, 180)
pencil.left(90)
pencil.goto(-150,3)
pencil.end_fill()
pencil.left(180)
pencil.color("black")
pencil.pendown()
pencil.pensize(10)
pencil.goto(-50,3)
pencil.penup()
pencil.goto(50,3)
pencil.pendown()
pencil.goto(150,3)
pencil.penup()
pencil.pensize(3)
pencil.goto(-25,0)
pencil.penup()
pencil.pencolor("#ff1a1a")
pencil.color("#ff1a1a")
pencil.goto(0,0)
pencil.pendown()
pencil.begin_fill()
pencil.circle(75)
pencil.end_fill()
pencil.penup()
pencil.goto()
pencil.color("#ffe6e6")
pencil.pencolor("black")
pencil.pencolor("black")
pencil.goto(0,-50)
pencil.pendown()
pencil.begin_fill()
pencil.circle(50)
pencil.end_fill()
pencil.penup()
pencil.goto(0,-25)
pencil.color("white")
pencil.pendown()
pencil.begin_fill()
pencil.circle(25)
pencil.end_fill()
pencil.penup()
pencil.goto(0,-150)
pencil.pendown()
pencil.pensize(12)
pencil.color("black")
pencil.circle(150)


turtle.exitonclick() #Keeps pycharm window open
